spring.config.activate.on-profile: test

spring:
  application:
    name: hhplus
  profiles:
    active: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:lecture;MODE=MySQL
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true